CREATE TABLE `law_book`.`blog` ( `id` INT NOT NULL , `title` VARCHAR(200) NOT NULL ,
`content` MEDIUMTEXT NOT NULL , `image` VARCHAR(100) NOT NULL , `media` VARCHAR(100) NOT NULL ,
`uploadDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;